// MeinAuftrag24 – Kundenbewertungen für Anbieter
(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const stars=n=>'★★★★★'.split('').map((x,i)=>`<span style="color:${i<Math.round(Number(n||0))?'#f5a623':'#d5d9e0'}">★</span>`).join('');
 async function reviewData(providerId){const {data,error}=await sb.from('reviews').select('id,rating,comment,created_at,customer_id').eq('provider_id',providerId).order('created_at',{ascending:false});if(error)return{rows:[],avg:0};const rows=data||[],avg=rows.length?rows.reduce((a,r)=>a+Number(r.rating),0)/rows.length:0;return{rows,avg};}
 async function badge(providerId){const d=await reviewData(providerId);return d.rows.length?`<span class="m24Rating" data-provider-reviews="${providerId}" title="Bewertungen ansehen">${stars(d.avg)} <b>${d.avg.toFixed(1)}</b> <span>(${d.rows.length} Bewertungen)</span></span>`:`<span class="m24Rating muted" data-provider-reviews="${providerId}">Noch keine Bewertungen</span>`;}
 async function show(providerId){const d=await reviewData(providerId);let box=document.getElementById('m24ReviewModal');if(!box){box=document.createElement('div');box.id='m24ReviewModal';document.body.appendChild(box);}box.innerHTML=`<div class="m24ReviewBackdrop"><div class="m24ReviewCard"><button class="m24ReviewClose" aria-label="Schliessen">×</button><h2>Kundenbewertungen</h2>${d.rows.length?`<div class="m24ReviewSummary">${stars(d.avg)} <b>${d.avg.toFixed(1)} von 5</b><div>${d.rows.length} verifizierte Bewertung${d.rows.length===1?'':'en'}</div></div>${d.rows.map(r=>`<div class="m24ReviewItem"><div>${stars(r.rating)} <b>${r.rating}/5</b></div>${r.comment?`<p>${esc(r.comment)}</p>`:''}<small>${new Date(r.created_at).toLocaleDateString('de-CH')}</small></div>`).join('')}`:'<p>Noch keine Bewertungen für diesen Anbieter.</p>'}</div></div>`;box.querySelector('.m24ReviewClose').onclick=()=>box.remove();box.querySelector('.m24ReviewBackdrop').onclick=e=>{if(e.target===e.currentTarget)box.remove();};}
 async function mountBadges(){document.querySelectorAll('[data-provider-id]').forEach(async el=>{if(el.querySelector('.m24Rating'))return;const id=el.dataset.providerId;if(!id)return;const h=el.querySelector('h3,h4,.providerName')||el;const x=document.createElement('div');x.innerHTML=await badge(id);h.insertAdjacentElement('afterend',x.firstElementChild);});document.querySelectorAll('[data-provider-reviews]').forEach(x=>x.onclick=()=>show(x.dataset.providerReviews));}
 async function mountCustomerReviewButtons(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();if(p?.role!=='customer')return;const {data:jobs}=await sb.from('jobs').select('id,title,status,assigned_provider_id').eq('customer_id',user.id).eq('status','completed').not('assigned_provider_id','is',null);for(const j of jobs||[]){const {data:old}=await sb.from('reviews').select('id').eq('job_id',j.id).eq('customer_id',user.id).maybeSingle();if(old)continue;const candidates=document.querySelectorAll(`[data-job-id="${j.id}"]`);candidates.forEach(el=>{if(el.querySelector('[data-review-job]'))return;const b=document.createElement('button');b.className='btn secondary small';b.dataset.reviewJob=j.id;b.dataset.provider=j.assigned_provider_id;b.textContent='⭐ Firma bewerten';b.onclick=()=>form(j.id,j.assigned_provider_id,j.title);(el.querySelector('.toolbar')||el).appendChild(b);});}}
 function form(jobId,providerId,title){let box=document.getElementById('m24ReviewModal');if(!box){box=document.createElement('div');box.id='m24ReviewModal';document.body.appendChild(box);}box.innerHTML=`<div class="m24ReviewBackdrop"><div class="m24ReviewCard"><button class="m24ReviewClose">×</button><h2>Firma bewerten</h2><p>${esc(title||'Abgeschlossener Auftrag')}</p><label>Bewertung<select id="m24Rating"><option value="5">★★★★★ – Sehr gut</option><option value="4">★★★★☆ – Gut</option><option value="3">★★★☆☆ – Okay</option><option value="2">★★☆☆☆ – Nicht gut</option><option value="1">★☆☆☆☆ – Schlecht</option></select></label><label>Kommentar<textarea id="m24ReviewComment" maxlength="1500" placeholder="Wie war die Zusammenarbeit mit der Firma?"></textarea></label><button id="m24ReviewSave" class="btn primary">Bewertung veröffentlichen</button><div id="m24ReviewMsg"></div></div></div>`;box.querySelector('.m24ReviewClose').onclick=()=>box.remove();document.getElementById('m24ReviewSave').onclick=async()=>{const rating=Number(document.getElementById('m24Rating').value),comment=document.getElementById('m24ReviewComment').value.trim(),msg=document.getElementById('m24ReviewMsg');const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('reviews').insert({job_id:jobId,customer_id:user.id,provider_id:providerId,rating,comment:comment||null});if(error){msg.innerHTML=`<div class="notice warn">${esc(error.message)}</div>`;return;}msg.innerHTML='<div class="notice ok">Danke! Deine Bewertung wurde veröffentlicht.</div>';setTimeout(()=>location.reload(),800);};}
 document.addEventListener('click',e=>{const x=e.target.closest('[data-provider-reviews]');if(x)show(x.dataset.providerReviews);});
 const css=document.createElement('style');css.textContent=`.m24Rating{display:inline-flex;gap:3px;align-items:center;cursor:pointer;font-size:14px;margin:5px 0}.m24Rating.muted{color:#697386}.m24ReviewBackdrop{position:fixed;inset:0;background:#0008;z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px}.m24ReviewCard{background:#fff;border-radius:18px;max-width:620px;width:100%;max-height:85vh;overflow:auto;padding:24px;position:relative}.m24ReviewClose{position:absolute;right:14px;top:10px;border:0;background:none;font-size:30px;cursor:pointer}.m24ReviewSummary{padding:14px;background:#f7f8fa;border-radius:12px;margin:12px 0}.m24ReviewItem{border-top:1px solid #e7e9ee;padding:14px 0}.m24ReviewItem p{white-space:pre-wrap}.m24ReviewCard label{display:grid;gap:6px;margin:14px 0}.m24ReviewCard textarea{min-height:110px}`;document.head.appendChild(css);
 const obs=new MutationObserver(()=>{mountBadges();mountCustomerReviewButtons();});document.addEventListener('DOMContentLoaded',()=>{mountBadges();mountCustomerReviewButtons();obs.observe(document.body,{childList:true,subtree:true});});if(document.readyState!=='loading'){mountBadges();mountCustomerReviewButtons();obs.observe(document.body,{childList:true,subtree:true});}
 window.m24ProviderReviews={show,badge};
})();