// MeinAuftrag24 – Mietfahrzeug-Inserate bearbeiten
(()=>{
 const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 async function me(){const {data:{user}}=await sb.auth.getUser();return user||null;}
 async function openEdit(id){const user=await me();if(!user)return;const {data:v,error}=await sb.from('rental_vehicles').select('*').eq('id',id).eq('provider_id',user.id).maybeSingle();if(error||!v){alert(error?.message||'Inserat nicht gefunden.');return;}let box=document.getElementById('rvEditBox');if(!box){box=document.createElement('div');box.id='rvEditBox';document.querySelector('#rentals .wrap')?.appendChild(box);}box.innerHTML=`<div class="card" style="margin-top:18px"><div class="row"><div><h3>✏️ Fahrzeug bearbeiten</h3><div class="meta">${e(v.title)}</div></div><button id="rvEditClose" class="btn ghost small">Schliessen</button></div><div class="formGrid" style="margin-top:14px"><label>Titel<input id="rveTitle" value="${e(v.title)}"></label><label>Standort<input id="rveLocation" value="${e(v.location)}"></label><label>Marke<input id="rveMake" value="${e(v.make||'')}"></label><label>Modell<input id="rveModel" value="${e(v.model||'')}"></label><label>Fahrzeugtyp<select id="rveType">${['Personenwagen','Transporter','Lieferwagen','Bus','SUV','Sonstiges'].map(x=>`<option ${v.vehicle_type===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Getriebe<select id="rveTransmission"><option value="automatic" ${v.transmission==='automatic'?'selected':''}>Automatik</option><option value="manual" ${v.transmission==='manual'?'selected':''}>Manuell</option></select></label><label>Sitzplätze<input id="rveSeats" type="number" min="1" value="${e(v.seats||'')}"></label><label>Tagespreis CHF<input id="rveDaily" type="number" min="0" step="0.01" value="${e(v.daily_rate||'')}"></label><label>Inklusive km / Tag<input id="rveKm" type="number" min="0" value="${e(v.included_km??0)}"></label><label>Preis pro Zusatz-km CHF<input id="rveExtra" type="number" min="0" step="0.01" value="${e(v.extra_km_rate??'')}"></label><label>Verfügbar von<input id="rveFrom" type="date" value="${e(v.available_from||'')}"></label><label>Verfügbar bis<input id="rveTo" type="date" value="${e(v.available_to||'')}"></label><label class="full">Beschreibung<textarea id="rveDesc">${e(v.description||'')}</textarea></label><div class="full"><button id="rvEditSave" class="btn primary">Änderungen speichern</button></div><div id="rvEditMsg" class="full"></div></div></div>`;
 document.getElementById('rvEditClose').onclick=()=>box.remove();
 document.getElementById('rvEditSave').onclick=()=>saveEdit(id,user.id);
 box.scrollIntoView({behavior:'smooth'});
 }
 async function saveEdit(id,userId){const msg=document.getElementById('rvEditMsg');const row={title:document.getElementById('rveTitle').value.trim(),location:document.getElementById('rveLocation').value.trim(),make:document.getElementById('rveMake').value.trim()||null,model:document.getElementById('rveModel').value.trim()||null,vehicle_type:document.getElementById('rveType').value,transmission:document.getElementById('rveTransmission').value,seats:Number(document.getElementById('rveSeats').value)||null,daily_rate:Number(document.getElementById('rveDaily').value)||0,included_km:Number(document.getElementById('rveKm').value)||0,extra_km_rate:document.getElementById('rveExtra').value?Number(document.getElementById('rveExtra').value):null,available_from:document.getElementById('rveFrom').value||null,available_to:document.getElementById('rveTo').value||null,description:document.getElementById('rveDesc').value.trim()||null,updated_at:new Date().toISOString()};if(!row.title||!row.location||!row.daily_rate){msg.innerHTML='<div class="notice warn">Bitte Titel, Standort und Tagespreis ausfüllen.</div>';return;}const {error}=await sb.from('rental_vehicles').update(row).eq('id',id).eq('provider_id',userId);if(error){msg.innerHTML=`<div class="notice warn">${e(error.message)}</div>`;return;}msg.innerHTML='<div class="notice ok">Änderungen gespeichert.</div>';setTimeout(()=>location.reload(),500);}
 function attach(){const root=document.getElementById('rentalList');if(!root)return;root.querySelectorAll('[data-rv-manage]').forEach(b=>{if(b.parentElement?.querySelector(`[data-rv-edit="${b.dataset.rvManage}"]`))return;const x=document.createElement('button');x.className='btn ghost small';x.dataset.rvEdit=b.dataset.rvManage;x.textContent='✏️ Bearbeiten';x.onclick=()=>openEdit(x.dataset.rvEdit);b.parentElement?.insertBefore(x,b);});}
 const obs=new MutationObserver(()=>attach());document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{const r=document.getElementById('rentalList');if(r){obs.observe(r,{childList:true,subtree:true});attach();}},1000));if(document.readyState!=='loading')setTimeout(()=>{const r=document.getElementById('rentalList');if(r){obs.observe(r,{childList:true,subtree:true});attach();}},1000);
})();